import {
  FICTIONIST_SCHEMA_VERSION,
  type FictionChapter,
  type FictionCanonEntry,
  type FictionistIndex,
  type FictionTimelineEvent,
} from './domain';

export interface FictionistSeedData {
  index: FictionistIndex;
  chapterContents: Record<string, string>;
}

const MIST_CHAPTERS: FictionChapter[] = [
  {
    id: 'chapter-1',
    projectId: 'mist-harbor',
    volumeId: 'mist-harbor-volume-1',
    title: '潮声之外',
    status: 'final',
    wordCount: 3280,
    revision: 1,
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-20T14:32:00.000Z',
  },
  {
    id: 'chapter-2',
    projectId: 'mist-harbor',
    volumeId: 'mist-harbor-volume-1',
    title: '没有靠岸的船',
    status: 'revised',
    wordCount: 2860,
    revision: 2,
    createdAt: '2026-06-03T08:00:00.000Z',
    updatedAt: '2026-07-21T14:32:00.000Z',
  },
  {
    id: 'chapter-3',
    projectId: 'mist-harbor',
    volumeId: 'mist-harbor-volume-1',
    title: '七号泊位',
    status: 'draft',
    wordCount: 1140,
    revision: 1,
    createdAt: '2026-06-05T08:00:00.000Z',
    updatedAt: '2026-07-23T14:32:00.000Z',
  },
  {
    id: 'chapter-4',
    projectId: 'mist-harbor',
    volumeId: 'mist-harbor-volume-1',
    title: '守钟人的名单',
    status: 'outline',
    wordCount: 0,
    revision: 0,
    createdAt: '2026-07-22T08:00:00.000Z',
    updatedAt: '2026-07-22T08:00:00.000Z',
  },
];

const NORTH_CHAPTERS: FictionChapter[] = Array.from({ length: 10 }, (_, index) => ({
  id: `north-window-chapter-${index + 1}`,
  projectId: 'north-window',
  volumeId: 'north-window-volume-1',
  title: `旧事 ${index + 1}`,
  status: 'final',
  wordCount: 4620,
  revision: 1,
  createdAt: '2026-05-01T08:00:00.000Z',
  updatedAt: '2026-06-18T08:00:00.000Z',
}));

const MIST_CANON_ENTRIES: FictionCanonEntry[] = [
  {
    id: 'canon-lin-yan',
    projectId: 'mist-harbor',
    type: 'character',
    name: '林砚',
    summary: '调查记者，正在追查三年前七号泊位的封闭真相。',
    content: '林砚擅长从旧报纸和航道记录中寻找矛盾。她收到蓝墨水来信后，决定亲自回到雾港。',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-23T14:32:00.000Z',
  },
  {
    id: 'canon-lao-du',
    projectId: 'mist-harbor',
    type: 'character',
    name: '老杜',
    summary: '港区值夜人，熟悉所有旧航道和钟塔的异常。',
    content: '老杜曾负责七号泊位的夜间巡查。停电当晚，他留下两杯热茶后失踪。',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-21T14:32:00.000Z',
  },
  {
    id: 'canon-mist-harbor',
    projectId: 'mist-harbor',
    type: 'location',
    name: '雾港',
    summary: '沿海工业港，常年受潮雾影响。',
    content: '雾港由旧海关、七号泊位和沿海工业区组成。港区停电时，所有机械钟会同时停止。',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-20T14:32:00.000Z',
  },
  {
    id: 'canon-old-customs-tower',
    projectId: 'mist-harbor',
    type: 'location',
    name: '旧海关钟塔',
    summary: '停电后仍在运行的机械钟塔。',
    content: '钟塔位于旧海关楼顶，钟面长期停在凌晨两点十四分，只有收到蓝墨水来信的人能听见它继续走动。',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-22T14:32:00.000Z',
  },
  {
    id: 'canon-beacon-office',
    projectId: 'mist-harbor',
    type: 'organization',
    name: '航标署',
    summary: '负责航道与灯塔维护的港务机构。',
    content: '航标署保存着所有登记航线和灯塔维修记录，但三年前的七号泊位资料被人为抽走。',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-18T14:32:00.000Z',
  },
  {
    id: 'canon-blue-ink-letter',
    projectId: 'mist-harbor',
    type: 'item',
    name: '蓝墨水来信',
    summary: '寄信人不明、指向七号泊位的线索。',
    content: '信纸受潮后会留下蓝色墨迹，内容要求林砚不要惊动守钟人，并暗示今晚不会有船靠岸。',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-23T14:32:00.000Z',
  },
];

const MIST_TIMELINE_EVENTS: FictionTimelineEvent[] = [
  {
    id: 'timeline-closure',
    projectId: 'mist-harbor',
    timeLabel: '三年前 · 10月',
    title: '七号泊位因事故永久封闭',
    description: '一场未公开的港区事故后，七号泊位被封锁，相关航道记录也被抽走。',
    kind: 'background',
    order: 0,
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-20T14:32:00.000Z',
  },
  {
    id: 'timeline-letter',
    projectId: 'mist-harbor',
    timeLabel: '七天前 · 22:40',
    title: '林砚收到没有邮戳的蓝墨水来信',
    description: '信件要求她不要惊动守钟人，并暗示今晚不会有船靠岸。',
    kind: 'confirmed',
    order: 1,
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-21T14:32:00.000Z',
  },
  {
    id: 'timeline-blackout',
    projectId: 'mist-harbor',
    timeLabel: '今晚 · 02:14',
    title: '港区停电，所有机械钟同时停止',
    description: '港区断电后，机械钟全部停在凌晨两点十四分，只有旧海关塔顶的铜钟仍在走。',
    kind: 'chapter',
    sourceChapterId: 'chapter-1',
    order: 2,
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-22T14:32:00.000Z',
  },
  {
    id: 'timeline-map',
    projectId: 'mist-harbor',
    timeLabel: '今晚 · 02:31',
    title: '林砚在值夜岗亭发现异常航道图',
    description: '航道图上出现一条不属于任何登记航线的红线，终点指向七号泊位。',
    kind: 'chapter',
    sourceChapterId: 'chapter-2',
    order: 3,
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-22T14:32:00.000Z',
  },
  {
    id: 'timeline-berth',
    projectId: 'mist-harbor',
    timeLabel: '今晚 · 02:46',
    title: '林砚进入七号泊位',
    description: '铁门没有上锁。她推门进入泊位，准备查明蓝墨水来信的真正来源。',
    kind: 'chapter',
    sourceChapterId: 'chapter-3',
    order: 4,
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-23T14:32:00.000Z',
  },
];

export function createDemoFictionistData(): FictionistSeedData {
  const chapters = [...MIST_CHAPTERS, ...NORTH_CHAPTERS];
  return {
    index: {
      schemaVersion: FICTIONIST_SCHEMA_VERSION,
      projects: {
        'mist-harbor': {
          id: 'mist-harbor',
          title: '雾港来信',
          genre: '长篇悬疑',
          status: 'drafting',
          volumeIds: ['mist-harbor-volume-1'],
          canonEntryCount: MIST_CANON_ENTRIES.length,
          coverTone: 'teal',
          createdAt: '2026-06-01T08:00:00.000Z',
          updatedAt: '2026-07-23T14:32:00.000Z',
        },
        'summer-orbit': {
          id: 'summer-orbit',
          title: '夏日轨道',
          genre: '青春科幻',
          status: 'paused',
          volumeIds: ['summer-orbit-volume-1'],
          canonEntryCount: 0,
          coverTone: 'blue',
          createdAt: '2026-07-20T08:00:00.000Z',
          updatedAt: '2026-07-22T21:08:00.000Z',
        },
        'north-window': {
          id: 'north-window',
          title: '北窗旧事',
          genre: '年代短篇集',
          status: 'archived',
          volumeIds: ['north-window-volume-1'],
          canonEntryCount: 0,
          coverTone: 'red',
          createdAt: '2026-04-01T08:00:00.000Z',
          updatedAt: '2026-06-18T08:00:00.000Z',
        },
      },
      volumes: {
        'mist-harbor-volume-1': {
          id: 'mist-harbor-volume-1',
          projectId: 'mist-harbor',
          title: '第一卷 · 潮汐失语',
          chapterIds: MIST_CHAPTERS.map((chapter) => chapter.id),
        },
        'summer-orbit-volume-1': {
          id: 'summer-orbit-volume-1',
          projectId: 'summer-orbit',
          title: '第一卷',
          chapterIds: [],
        },
        'north-window-volume-1': {
          id: 'north-window-volume-1',
          projectId: 'north-window',
          title: '旧事',
          chapterIds: NORTH_CHAPTERS.map((chapter) => chapter.id),
        },
      },
      chapters: Object.fromEntries(chapters.map((chapter) => [chapter.id, chapter])),
      canonEntries: Object.fromEntries(
        MIST_CANON_ENTRIES.map((entry) => [entry.id, entry]),
      ),
      timelineEvents: Object.fromEntries(
        MIST_TIMELINE_EVENTS.map((event) => [event.id, event]),
      ),
      activeProjectId: 'mist-harbor',
      activeChapterId: 'chapter-3',
      updatedAt: '2026-07-23T14:32:00.000Z',
    },
    chapterContents: {
      'chapter-1': '港区停电后的第十七分钟，林砚终于听见了那封信里提到的钟声。\n\n声音从雾里传来，隔着废弃的引水渠，一下，又一下。码头所有机械钟都停在凌晨两点十四分，只有旧海关塔顶的铜钟仍在走。\n\n她把信纸折回原样，塞进外套内袋。纸角擦过指尖时，留下了一点潮湿的蓝色墨迹。寄信人知道她会来，也知道今晚不会有船靠岸。',
      'chapter-2': '林砚沿着防波堤向东走。雾把灯塔切成两截，上半截悬在黑暗里，像一枚没有落下的句号。\n\n值夜人老杜不在岗亭，桌上却摆着两杯刚泡好的茶。第二只杯子下面压着一张航道图，图上有一条不属于任何登记航线的红线。\n\n红线的终点，是三年前已经封闭的七号泊位。',
      'chapter-3': '七号泊位的铁门没有上锁。\n\n林砚推门时，门轴发出的声音和信里那句“不要惊动守钟人”同时浮进脑海。她停了一秒，还是走了进去。',
      'chapter-4': '',
      ...Object.fromEntries(NORTH_CHAPTERS.map((chapter) => [chapter.id, ''])),
    },
  };
}
